### PR TITLE
Handle edge cases: Unscrubbed disk and script not running as root

### PR DESCRIPTION
**Pull request by PeterBortas**
- Unless we are running as root, use sudo.
- If the disk has never been scrubbed, set last scrub to epoch.

### CODE REVIEW

**Comment by PeterBortas** [comment]
Might be more of an RFC. It complicates the code a bit and forces sudo if you aren't already root. But it's what I use and solves what I need solved.

**Comment by Josef-Friedrich** [comment]
Thank you very much for your pull request. Would you be so nice to adopt the tests. Then I would like to merge your code.

**Comment by PeterBortas** [comment]
Completely missed that there was a testsuite.

Test failures fixed by removing the automatic attempt to use sudo. There is now a -r/--sudo flag that forces use of sudo. Also included sudoers.d/zfs-history that can be copied to /etc/sudorers.d/ to enable sudo access to "zpool history" for the users "nagios" and "nrpe".

**Comment by Josef-Friedrich** [comment]
Thank you very much!

**Comment by Josef-Friedrich** [comment]
@valgrind  In 24238afce4959d861e26176a0ae6bab76ff3ca05 I tried to simplify your implementation of the `--sudo` option. Does 24238afce4959d861e26176a0ae6bab76ff3ca05 still work for you?

**Pull request merged**
